#############################################################################
# Makefile for building: sim86
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Sep 20 22:01:47 2009
# Project:  sim86.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile sim86.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		FlagsWidget.cc \
		GeneralRegistersWidget.cc \
		SegmentRegistersWidget.cc \
		StackWidget.cc \
		DisassemblyWidget.cc \
		MemoryWidget.cc \
		TerminalWidget.cc \
		Sim86Window.cc moc_FlagsWidget.cpp \
		moc_GeneralRegistersWidget.cpp \
		moc_SegmentRegistersWidget.cpp \
		moc_StackWidget.cpp \
		moc_DisassemblyWidget.cpp \
		moc_MemoryWidget.cpp \
		moc_TerminalWidget.cpp \
		moc_Sim86Window.cpp
OBJECTS       = main.o \
		FlagsWidget.o \
		GeneralRegistersWidget.o \
		SegmentRegistersWidget.o \
		StackWidget.o \
		DisassemblyWidget.o \
		MemoryWidget.o \
		TerminalWidget.o \
		Sim86Window.o \
		moc_FlagsWidget.o \
		moc_GeneralRegistersWidget.o \
		moc_SegmentRegistersWidget.o \
		moc_StackWidget.o \
		moc_DisassemblyWidget.o \
		moc_MemoryWidget.o \
		moc_TerminalWidget.o \
		moc_Sim86Window.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		sim86.pro
QMAKE_TARGET  = sim86
DESTDIR       = 
TARGET        = sim86

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_FlagsWidget.h ui_GeneralRegistersWidget.h ui_SegmentRegistersWidget.h ui_StackWidget.h ui_DisassemblyWidget.h ui_MemoryWidget.h ui_TerminalWidget.h ui_Sim86Window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sim86.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile sim86.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile sim86.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sim861.0.0 || $(MKDIR) .tmp/sim861.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sim861.0.0/ && $(COPY_FILE) --parents FlagsWidget.hh GeneralRegistersWidget.hh SegmentRegistersWidget.hh StackWidget.hh DisassemblyWidget.hh MemoryWidget.hh TerminalWidget.hh Sim86Window.hh .tmp/sim861.0.0/ && $(COPY_FILE) --parents main.cc FlagsWidget.cc GeneralRegistersWidget.cc SegmentRegistersWidget.cc StackWidget.cc DisassemblyWidget.cc MemoryWidget.cc TerminalWidget.cc Sim86Window.cc .tmp/sim861.0.0/ && $(COPY_FILE) --parents FlagsWidget.ui GeneralRegistersWidget.ui SegmentRegistersWidget.ui StackWidget.ui DisassemblyWidget.ui MemoryWidget.ui TerminalWidget.ui Sim86Window.ui .tmp/sim861.0.0/ && (cd `dirname .tmp/sim861.0.0` && $(TAR) sim861.0.0.tar sim861.0.0 && $(COMPRESS) sim861.0.0.tar) && $(MOVE) `dirname .tmp/sim861.0.0`/sim861.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sim861.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_FlagsWidget.cpp moc_GeneralRegistersWidget.cpp moc_SegmentRegistersWidget.cpp moc_StackWidget.cpp moc_DisassemblyWidget.cpp moc_MemoryWidget.cpp moc_TerminalWidget.cpp moc_Sim86Window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_FlagsWidget.cpp moc_GeneralRegistersWidget.cpp moc_SegmentRegistersWidget.cpp moc_StackWidget.cpp moc_DisassemblyWidget.cpp moc_MemoryWidget.cpp moc_TerminalWidget.cpp moc_Sim86Window.cpp
moc_FlagsWidget.cpp: ui_FlagsWidget.h \
		FlagsWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FlagsWidget.hh -o moc_FlagsWidget.cpp

moc_GeneralRegistersWidget.cpp: ui_GeneralRegistersWidget.h \
		GeneralRegistersWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GeneralRegistersWidget.hh -o moc_GeneralRegistersWidget.cpp

moc_SegmentRegistersWidget.cpp: ui_SegmentRegistersWidget.h \
		SegmentRegistersWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SegmentRegistersWidget.hh -o moc_SegmentRegistersWidget.cpp

moc_StackWidget.cpp: ui_StackWidget.h \
		StackWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) StackWidget.hh -o moc_StackWidget.cpp

moc_DisassemblyWidget.cpp: ui_DisassemblyWidget.h \
		DisassemblyWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) DisassemblyWidget.hh -o moc_DisassemblyWidget.cpp

moc_MemoryWidget.cpp: ui_MemoryWidget.h \
		MemoryWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MemoryWidget.hh -o moc_MemoryWidget.cpp

moc_TerminalWidget.cpp: ui_FlagsWidget.h \
		TerminalWidget.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TerminalWidget.hh -o moc_TerminalWidget.cpp

moc_Sim86Window.cpp: ui_Sim86Window.h \
		FlagsWidget.hh \
		ui_FlagsWidget.h \
		GeneralRegistersWidget.hh \
		ui_GeneralRegistersWidget.h \
		SegmentRegistersWidget.hh \
		ui_SegmentRegistersWidget.h \
		StackWidget.hh \
		ui_StackWidget.h \
		DisassemblyWidget.hh \
		ui_DisassemblyWidget.h \
		MemoryWidget.hh \
		ui_MemoryWidget.h \
		Sim86Window.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Sim86Window.hh -o moc_Sim86Window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_FlagsWidget.h ui_GeneralRegistersWidget.h ui_SegmentRegistersWidget.h ui_StackWidget.h ui_DisassemblyWidget.h ui_MemoryWidget.h ui_TerminalWidget.h ui_Sim86Window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_FlagsWidget.h ui_GeneralRegistersWidget.h ui_SegmentRegistersWidget.h ui_StackWidget.h ui_DisassemblyWidget.h ui_MemoryWidget.h ui_TerminalWidget.h ui_Sim86Window.h
ui_FlagsWidget.h: FlagsWidget.ui
	/usr/bin/uic-qt4 FlagsWidget.ui -o ui_FlagsWidget.h

ui_GeneralRegistersWidget.h: GeneralRegistersWidget.ui
	/usr/bin/uic-qt4 GeneralRegistersWidget.ui -o ui_GeneralRegistersWidget.h

ui_SegmentRegistersWidget.h: SegmentRegistersWidget.ui
	/usr/bin/uic-qt4 SegmentRegistersWidget.ui -o ui_SegmentRegistersWidget.h

ui_StackWidget.h: StackWidget.ui
	/usr/bin/uic-qt4 StackWidget.ui -o ui_StackWidget.h

ui_DisassemblyWidget.h: DisassemblyWidget.ui
	/usr/bin/uic-qt4 DisassemblyWidget.ui -o ui_DisassemblyWidget.h

ui_MemoryWidget.h: MemoryWidget.ui
	/usr/bin/uic-qt4 MemoryWidget.ui -o ui_MemoryWidget.h

ui_TerminalWidget.h: TerminalWidget.ui
	/usr/bin/uic-qt4 TerminalWidget.ui -o ui_TerminalWidget.h

ui_Sim86Window.h: Sim86Window.ui
	/usr/bin/uic-qt4 Sim86Window.ui -o ui_Sim86Window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cc Sim86Window.hh \
		ui_Sim86Window.h \
		FlagsWidget.hh \
		ui_FlagsWidget.h \
		GeneralRegistersWidget.hh \
		ui_GeneralRegistersWidget.h \
		SegmentRegistersWidget.hh \
		ui_SegmentRegistersWidget.h \
		StackWidget.hh \
		ui_StackWidget.h \
		DisassemblyWidget.hh \
		ui_DisassemblyWidget.h \
		MemoryWidget.hh \
		ui_MemoryWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

FlagsWidget.o: FlagsWidget.cc FlagsWidget.hh \
		ui_FlagsWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlagsWidget.o FlagsWidget.cc

GeneralRegistersWidget.o: GeneralRegistersWidget.cc GeneralRegistersWidget.hh \
		ui_GeneralRegistersWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GeneralRegistersWidget.o GeneralRegistersWidget.cc

SegmentRegistersWidget.o: SegmentRegistersWidget.cc SegmentRegistersWidget.hh \
		ui_SegmentRegistersWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SegmentRegistersWidget.o SegmentRegistersWidget.cc

StackWidget.o: StackWidget.cc StackWidget.hh \
		ui_StackWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StackWidget.o StackWidget.cc

DisassemblyWidget.o: DisassemblyWidget.cc DisassemblyWidget.hh \
		ui_DisassemblyWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DisassemblyWidget.o DisassemblyWidget.cc

MemoryWidget.o: MemoryWidget.cc MemoryWidget.hh \
		ui_MemoryWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemoryWidget.o MemoryWidget.cc

TerminalWidget.o: TerminalWidget.cc TerminalWidget.hh \
		ui_FlagsWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TerminalWidget.o TerminalWidget.cc

Sim86Window.o: Sim86Window.cc Sim86Window.hh \
		ui_Sim86Window.h \
		FlagsWidget.hh \
		ui_FlagsWidget.h \
		GeneralRegistersWidget.hh \
		ui_GeneralRegistersWidget.h \
		SegmentRegistersWidget.hh \
		ui_SegmentRegistersWidget.h \
		StackWidget.hh \
		ui_StackWidget.h \
		DisassemblyWidget.hh \
		ui_DisassemblyWidget.h \
		MemoryWidget.hh \
		ui_MemoryWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sim86Window.o Sim86Window.cc

moc_FlagsWidget.o: moc_FlagsWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FlagsWidget.o moc_FlagsWidget.cpp

moc_GeneralRegistersWidget.o: moc_GeneralRegistersWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GeneralRegistersWidget.o moc_GeneralRegistersWidget.cpp

moc_SegmentRegistersWidget.o: moc_SegmentRegistersWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SegmentRegistersWidget.o moc_SegmentRegistersWidget.cpp

moc_StackWidget.o: moc_StackWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StackWidget.o moc_StackWidget.cpp

moc_DisassemblyWidget.o: moc_DisassemblyWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DisassemblyWidget.o moc_DisassemblyWidget.cpp

moc_MemoryWidget.o: moc_MemoryWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MemoryWidget.o moc_MemoryWidget.cpp

moc_TerminalWidget.o: moc_TerminalWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TerminalWidget.o moc_TerminalWidget.cpp

moc_Sim86Window.o: moc_Sim86Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Sim86Window.o moc_Sim86Window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

